### ISSUE TITLE
Any plans to implement TAP?

### ISSUE THREAD

**Issue by alexvnesta** [bigtreetech/Eddy#66] opened 2024-09-10 20:32 UTC
Are there plans to implement eddy tap support?

Cartographer3Ds implementation for TAP is open source and documented, 
Firmware enabling tap feature (For STM32, not rp2040):
https://github.com/Klipper3d/klipper/commit/ee5df5521eb56d3e4cd33f9c14c2457daef0068a
Plugin:
https://github.com/Cartographer3D/cartographer-klipper

Also, It looks like KevinOConnor has a an implementation for eddy sensor tap support, but potentially needs more refinement.

https://github.com/KevinOConnor/klipper-dev/tree/work-ldctap-20240430

**Comment by looxonline** [comment] 2024-09-11 06:52
Duplicate of #43 

Work is scheduled for this.

**Closed by looxonline** 2024-09-11 06:52 UTC
Labels: duplicate
