### ISSUE TITLE
Error on 'PROBE_EDDY_CURRENT_CALIBRATE': missing CHIP

### ISSUE THREAD

**Issue by maj0r1337** [bigtreetech/Eddy#75] opened 2024-09-28 11:41 UTC
hi there,

ive got this message in mainsail when i try to run the macro PROBE EDDY CURRENT CALIBRATE AUTO > Error on 'PROBE_EDDY_CURRENT_CALIBRATE': missing CHIP

best regards

**Comment by bigtreetech** [comment] 2024-09-28 12:59
Duplicate of #58 and #69  and solved there.

**Closed by bigtreetech** 2024-09-28 12:59 UTC
Labels: duplicate

**Comment by Dinhson178** [comment] 2024-10-29 15:21
dear BTT. This is error macro Probe_eddy_current_calibrate_auto. You need fix it
